service: wine-events-api

provider:
  name: aws
  runtime: nodejs18.x
  region: us-east-1
  environment:
    DB_HOST: ${env:DB_HOST}
    DB_USERNAME: ${env:DB_USERNAME}
    DB_PASSWORD: ${env:DB_PASSWORD}
    DB_DATABASE: ${env:DB_DATABASE}
  httpApi:
    cors: true

plugins:
  - serverless-dotenv-plugin

package:
  patterns:
    - '!**/*'
    - 'dist/**'
    - 'node_modules/**'
    - 'package.json'
    - 'package-lock.json'

functions:
  api:
    handler: dist/lambda.handler
    memorySize: 512
    timeout: 30
    vpc:
      securityGroupIds:
        - [your-security-group-id]
      subnetIds:
        - [your-subnet-id]
    events:
      - httpApi:
          path: /api/{proxy+}
          method: '*'
      - httpApi:
          path: /images/{proxy+}
          method: GET
      - httpApi:
          path: /api-docs
          method: GET

# plugins:  # Comment out for production deployment
#   - serverless-offline
#   - serverless-dotenv-plugin 